### ISSUE TITLE
uuid dependency

### ISSUE THREAD

**Issue by tverlaan** [marcelog/elixir_mod_event#1]
Hi,

I see you have uuid listed as a dependency but I don't see it used anywhere. Did you have any plans on using it? The latest version of uuid is 1.0.1 which I'm trying to use, but it breaks because of a mismatch in version numbers when also using elixir_mod_event as dependency.
I'd be happy to create a PR, but it seems so small and I don't know in which direction you want to go (removing or 'upgrading').

```
Looking up alternatives for conflicting requirements on uuid
  Activated version: 1.0.1
  From elixir_mod_event v0.0.3: ~> 0.1.5
  From mix.exs: ~> 1.0.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

Thanks!

**Comment by marcelog** [comment]
Hello @tverlaan,

Yeah, it's being used here: https://github.com/marcelog/elixir_mod_event/blob/master/lib/elixir_mod_event/connection.ex#L320 so we can track background api commands.

I think we could use that version, the API doesn't seem to have changed for what we're using it (`UUID.uuid4` is still there). 

Let me check that out and get back to you. Also, please feel free to do that on your own too (by changing the elixir_mod_event mix.exs file), so we get an extra pair of eyes, and extra feedback is always welcome!

Stay tuned. Thanks for the report!

**Comment by tverlaan** [comment]
I guess I overlooked with grep :-). Thanks!

I'm using `UUID.uuid4` as well and it works fine. I've created a PR for you.

**Comment by marcelog** [comment]
Oh I just commited, and took the chance to update mix.lock too. Also, I specified `~> 1.0` for uuid.

Thanks for the contribution!

**Comment by marcelog** [comment]
Version 0.0.4 should work for you, it's just been published.

**Comment by tverlaan** [comment]
Even better. Thanks!
